version: '3'
services:
  db:
    container_name: maria-db
    image: mariadb:10
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: oms
      MYSQL_PASSWORD: oms
      MYSQL_ROOT_PASSWORD: oms
      TZ: Asia/Seoul
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306"
    restart: always
  app:
    container_name: spring-app
    image: openjdk:11-jdk
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
      #- $HOME/.m2:/root/.m2
    working_dir: /app
    command: sh start.sh
    depends_on:
      - db
    restart: always