spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    driver-class-name: org.mariadb.jdbc.Driver
    username: YOUR DB ID
    password: YOUR DB PASSWORD
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: YOUR GMAIL ID
    password: YOUR GMAIL PASSWORD
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  ssl:
    enabled: true
    key-store: classpath:oms1.keystore
    key-store-password: omsoms
  port: 7000
  error:
    whitelabel:
      enabled: false

# Please enter the FQDN of the RP
ompass:
  rp:
    fqdn: "https://www.example.com"
