spring:
  profiles:
    active: docker

logging:
  config: classpath:logging-config.xml

# Please enter a secret key assigned to the application
ompass:
  secret:
    key: 7fdcdc7596ee1337eb9fab6b6d40d49dffed33d399845e21c780605d17a6582e




